# Generated by Django 3.0.10 on 2020-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='quantity',
        ),
        migrations.AddField(
            model_name='offer',
            name='Offer_type',
            field=models.CharField(choices=[('buy', 'buy'), ('sale', 'sale')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'In process'), (2, 'Done')], default=0),
        ),
    ]
