# Generated by Django 3.0.10 on 2020-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_offer_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Current quantity'),
        ),
    ]
