# Generated by Django 3.0.10 on 2020-11-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201104_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Offer_type',
            new_name='offer_type',
        ),
    ]
