# Generated by Django 3.0.10 on 2020-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201116_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[(1, 1), (2, 2)], max_length=5),
        ),
    ]
