# Generated by Django 3.0.10 on 2020-11-18 09:39

from django.db import migrations
from django.contrib.auth.models import User


def checking_and_creating_inventory(apps, schema_editor):
    Inventory = apps.get_model('app', 'Inventory')
    Item = apps.get_model('app', 'Item')
    for user in User.objects.all():
        for item in Item.objects.all():
            Inventory.objects.get_or_create(
                user=user,
                item=item,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201117_1440'),
    ]

    operations = [
        migrations.RunPython(checking_and_creating_inventory),
    ]
