# Generated by Django 3.0.10 on 2020-11-18 10:30

from django.db import migrations
from django.contrib.auth.models import User


def checking_and_creating_inventory(apps, schema_editor):
    Inventory = apps.get_model('app', 'Inventory')
    Item = apps.get_model('app', 'Item')
    for user in User.objects.all():
        for item in Item.objects.all():
            Inventory.objects.get_or_create(
                user_id=user.id,
                item_id=item.id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201118_0939'),
    ]

    operations = [
        migrations.RunPython(checking_and_creating_inventory),
    ]
