# Generated by Django 3.0.10 on 2020-11-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='item',
            field=models.ManyToManyField(to='app.Item', verbose_name='item'),
        ),
    ]
