# Generated by Django 3.0.10 on 2020-11-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_permissiontype_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.Office'),
        ),
    ]
