# Generated by Django 3.0.10 on 2020-11-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201124_1226'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='role',
            managers=[
            ],
        ),
    ]
