version: '3'
services:
  web:
    build: .
    command: >
      bash -c "python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=dev
  celery:
    build: .
    command: celery -A TP worker -B
    volumes:
        - .:/app
    environment:
        - DEBUG=1
        - DJANGO_SETTINGS_MODULE=dev
        - DJANGO_ALLOWED_HOSTS=localhost:8000[::1]
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
        - web
        - redis
        - db
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - .TP-redis:/data
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
#  celery:
#    build: ./project
#    command: celery worker --app=core --loglevel=info
#    volumes:
#      - ./project:/usr/src/app
#    environment:
#      - DEBUG=1
#      - SECRET_KEY=fips#an4cpp845ywb&-jtn@t!(+k(4-4v6nm_#l+$u0huc6l9f
#      - DJANGO_ALLOWED_HOSTS=localhost:8000[::1]
#      - CELERY_BROKER=redis://redis:6379/0
#      - CELERY_BACKEND=redis://redis:6379/0
#    depends_on:
#      - web
#      - redis

