version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - web-variables.env
  celery:
    build: .
    command: celery -A trading_platform worker -B
    volumes:
        - .:/app
    env_file:
      - web-variables.env
    depends_on:
        - web
        - redis
        - db
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - trading_platform-redis:/data
  db:
    image: 'postgres:latest'
    env_file:
      - web-variables.env
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
